"""Ingest HTTP route tests (TASK-033 Issue 02): `POST /v1/ingest` +
`GET /v1/ingest/{document_id}`, wired to `ingest/pipeline.py`'s already-built
pipeline. `client`/`ingest_client`/`fake_pipeline_deps`/`fake_scheduler`/
`job_store`/`mock_session`/`admin_api_key` fixtures live in
tests/api/conftest.py.
"""

from __future__ import annotations

import json
import logging
import uuid
from collections.abc import Callable
from pathlib import Path
from unittest.mock import MagicMock

import pytest
from fastapi.testclient import TestClient
from pydantic import ValidationError
from qdrant_client import QdrantClient

from acl.ingest_stub import EffectiveACL
from api.ingest_routes import (
    ACLOverride,
    get_background_pipeline_deps_factory,
    get_pipeline_dependencies,
    get_session,
)
from api.main import app
from ingest.embedding import FakeEmbeddingClient
from ingest.identity import DocumentIdentity
from ingest.job_store import InMemoryJobStore
from ingest.pipeline import PipelineDependencies
from ingest.qdrant_setup import build_collection_name, create_collection
from ingest.task_scheduler import FakeTaskScheduler
from ingest.tokenizer import FakeTokenizer

VALID_ACL_OVERRIDE = json.dumps(
    {"allow_principals": ["group:eng"], "deny_principals": [], "security_label": "internal"}
)


def _auth_headers(admin_api_key: str) -> dict[str, str]:
    return {"X-Admin-Api-Key": admin_api_key}


def _upload(
    client: TestClient,
    admin_api_key: str,
    *,
    content_type: str = "text/plain",
    filename: str = "doc.txt",
    content: bytes = b"hello world",
    acl_override: str | None = VALID_ACL_OVERRIDE,
    repository_id: str = "default",
    headers: dict[str, str] | None = None,
):
    data = {"repository_id": repository_id}
    if acl_override is not None:
        data["acl_override"] = acl_override
    return client.post(
        "/v1/ingest",
        files={"file": (filename, content, content_type)},
        data=data,
        headers=_auth_headers(admin_api_key) if headers is None else headers,
    )


def test_schedules_background(
    ingest_client: TestClient,
    admin_api_key: str,
    fake_scheduler: FakeTaskScheduler,
    caplog: pytest.LogCaptureFixture,
) -> None:
    with caplog.at_level(logging.WARNING):
        response = _upload(ingest_client, admin_api_key)

    assert response.status_code == 200
    assert len(fake_scheduler.scheduled) == 1
    assert "scheduled for background processing" in caplog.text
    assert "TASK-010" in caplog.text


class _AllowAllACLLookup:
    """Minimal permissive `ACLLookup` for
    `test_background_task_uses_independent_session` only -- unlike
    `acl.ingest_stub.FakeACLLookup`, doesn't require pre-seeding a specific
    `(document_id, version_id)` pair, since that test's ids are generated by
    the route handler itself and aren't known ahead of the `POST` call. That
    test verifies session-lifecycle wiring, not ACL correctness."""

    def get_effective_acl(self, identity: DocumentIdentity) -> EffectiveACL:
        return EffectiveACL(allow_principals=["group:eng"], deny_principals=[], security_label="internal")

    def get_retention_state(self, identity: DocumentIdentity) -> str:
        return "active"


def test_background_task_uses_independent_session(
    client: TestClient, admin_api_key: str, tmp_path: Path
) -> None:
    """Regression test for a peer-review finding (2026-07-16): the
    background task must not reuse the request's own `Depends(get_session)`
    session -- its commit/close timing is tied to the request's response
    lifecycle, not the background task's own need to read/write durably (see
    `api/ingest_routes.py`'s module docstring for the full story). Does not
    use the `ingest_client` fixture -- that fixture always schedules via
    `FakeTaskScheduler`, which records the closure without running it, so it
    can't observe this. This test leaves `get_task_scheduler` on its real
    `BackgroundTasksScheduler` adapter instead, which this repo's TestClient
    drives to completion before `client.post(...)` returns (documented
    limitation, this file's own module docstring / Issue 02's risk review)
    -- exactly what makes the closure's real behavior observable here
    without a live Postgres.
    """
    request_session = MagicMock()
    request_session.execute.return_value.scalar_one_or_none.return_value = "test-embedding-model-v1"

    job_store = InMemoryJobStore()
    qdrant_client = QdrantClient(":memory:")
    # resolve_index_target() reads request_session's mocked "embedding"
    # model version below; the collection name it builds must already exist
    # -- create_collection() isn't idempotent/auto-called by the pipeline
    # itself (ingest/qdrant_setup.py's own docstring), matching
    # tests/ingest/test_pipeline.py's own `_make_target` helper.
    create_collection(qdrant_client, build_collection_name("default", "test-embedding-model-v1"))
    shared_fake_deps = PipelineDependencies(
        tokenizer=FakeTokenizer(),
        job_store=job_store,
        acl_lookup=_AllowAllACLLookup(),
        embedding_client=FakeEmbeddingClient(),
        qdrant_client=qdrant_client,
        # Not the `./ingest_checkpoints` default -- tests/ingest/test_pipeline.py's
        # own `_make_deps` helper uses `tmp_path` for the same reason: a real
        # pipeline run here actually calls write_checkpoint().
        checkpoint_dir=tmp_path,
    )

    background_sessions: list[MagicMock] = []

    def _factory() -> tuple[PipelineDependencies, MagicMock]:
        bg_session = MagicMock()
        background_sessions.append(bg_session)
        return shared_fake_deps, bg_session

    app.dependency_overrides[get_pipeline_dependencies] = lambda: shared_fake_deps
    app.dependency_overrides[get_session] = lambda: request_session
    app.dependency_overrides[get_background_pipeline_deps_factory] = lambda: _factory
    try:
        response = _upload(client, admin_api_key)
    finally:
        app.dependency_overrides.pop(get_pipeline_dependencies, None)
        app.dependency_overrides.pop(get_session, None)
        app.dependency_overrides.pop(get_background_pipeline_deps_factory, None)

    assert response.status_code == 200

    # The request's own session commits synchronously, before the response
    # is returned -- durable for the background task's independent session
    # to see, whichever of the two actually runs first.
    request_session.commit.assert_called_once()

    # The background task got its own session from the factory -- distinct
    # from the request's -- and finalized it.
    assert len(background_sessions) == 1
    bg_session = background_sessions[0]
    assert bg_session is not request_session
    bg_session.commit.assert_called_once()
    bg_session.close.assert_called_once()

    # And the pipeline actually ran to completion through the *real*
    # BackgroundTasksScheduler adapter -- P.1's own observation that this
    # path was "entirely untested" no longer holds.
    document_id = uuid.UUID(response.json()["document_id"])
    assert job_store.get_status(document_id) == "complete"


def test_returns_document_id_and_status_url(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key)

    assert response.status_code == 200
    body = response.json()
    assert "document_id" in body
    assert body["status_url"] == f"/v1/ingest/{body['document_id']}"
    assert body["status_url"].startswith("/v1/ingest/")
    assert not body["status_url"].startswith("http")


def test_rejects_unsupported_mime_type(
    ingest_client: TestClient, admin_api_key: str, fake_scheduler: FakeTaskScheduler
) -> None:
    response = _upload(ingest_client, admin_api_key, content_type="image/png", filename="doc.png")

    assert response.status_code == 415
    body = response.json()
    assert body["error"]["code"] == "unsupported_media_type"
    supported = body["error"]["details"]["supported_formats"]
    assert "text/plain" in supported
    assert "application/pdf" in supported
    assert len(fake_scheduler.scheduled) == 0


def test_missing_acl_override_returns_400(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key, acl_override=None)

    assert response.status_code == 400
    assert response.json()["error"]["code"] == "invalid_request"


def test_invalid_acl_override_returns_400(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key, acl_override="not valid json")

    assert response.status_code == 400
    assert response.json()["error"]["code"] == "invalid_request"


@pytest.mark.parametrize(
    ("seeded_phase", "seeded_progress", "expected_status"),
    [
        ("pending", 0.0, "pending"),
        ("parsed", 0.2, "parsing"),
        ("chunked", 0.4, "parsing"),
        ("indexing", 0.7, "indexing"),
        ("ready", 1.0, "ready"),
        ("failed", 0.4, "failed"),
    ],
)
def test_status_mapping(
    ingest_client: TestClient,
    admin_api_key: str,
    job_store: InMemoryJobStore,
    seeded_phase: str,
    seeded_progress: float,
    expected_status: str,
) -> None:
    job_id = job_store.create_job("ingest")
    job_store.advance(job_id, {"phase": seeded_phase, "progress": seeded_progress})
    if seeded_phase == "failed":
        job_store.advance(job_id, {"errors": ["some internal stack trace, /etc/secret/path"]})

    response = ingest_client.get(f"/v1/ingest/{job_id}", headers=_auth_headers(admin_api_key))

    assert response.status_code == 200
    body = response.json()
    assert body["status"] == expected_status
    assert body["progress"] == seeded_progress
    if expected_status == "failed":
        # Redaction: the raw internal error text must never cross the HTTP
        # boundary (docs/coding-standards.md's error-handling rule; flagged
        # in advance by JobStore.fail()'s own docstring, code review 2026-07-15).
        assert "internal stack trace" not in json.dumps(body)
        assert "/etc/secret/path" not in json.dumps(body)
        assert len(body["errors"]) == 1
    else:
        assert body["errors"] == []


def test_unknown_id_returns_404(ingest_client: TestClient, admin_api_key: str) -> None:
    response = ingest_client.get(
        "/v1/ingest/00000000-0000-0000-0000-000000000000", headers=_auth_headers(admin_api_key)
    )

    assert response.status_code == 404
    assert response.json()["error"]["code"] == "not_found"


def test_requires_auth_post_missing_credentials(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key, headers={})
    assert response.status_code == 401


def test_requires_auth_post_invalid_admin_key(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key, headers={"X-Admin-Api-Key": "wrong-key"})
    assert response.status_code == 401


def test_requires_auth_post_accepts_admin_key(ingest_client: TestClient, admin_api_key: str) -> None:
    response = _upload(ingest_client, admin_api_key)
    assert response.status_code == 200


def test_requires_auth_post_accepts_jwt(
    ingest_client: TestClient, jwt_headers: Callable[[], dict[str, str]]
) -> None:
    response = _upload(ingest_client, "", headers=jwt_headers())
    assert response.status_code == 200


def test_requires_auth_get_missing_credentials(ingest_client: TestClient) -> None:
    response = ingest_client.get("/v1/ingest/00000000-0000-0000-0000-000000000000")
    assert response.status_code == 401


def test_requires_auth_get_accepts_jwt(
    ingest_client: TestClient, jwt_headers: Callable[[], dict[str, str]], job_store: InMemoryJobStore
) -> None:
    job_id = job_store.create_job("ingest")
    response = ingest_client.get(f"/v1/ingest/{job_id}", headers=jwt_headers())
    assert response.status_code == 200


def test_acl_override_shape_requires_security_label() -> None:
    # Narrowed from a bare `pytest.raises(Exception)` (test-audit, 2026-07-16)
    # -- too broad to distinguish "correctly rejected as invalid" from "raised
    # for an unrelated reason", the one occurrence of that pattern in this suite.
    with pytest.raises(ValidationError):
        ACLOverride.model_validate({"allow_principals": ["x"]})
